// Data
export const NOTIFICATION_CONNECT_WS = 'NOTIFICATION_CONNECT_WS'
export const GET_DATA = 'GET_DATA'
export const UPDATE_DATA = 'UPDATE_DATA'

export const LOAD_BARBERS = 'LOAD_BARBERS'
export const LOAD_CUSTOMERS = 'LOAD_CUSTOMERS'

export const NOTIFICATIONS_LOADING = 'NOTIFICATIONS_LOADING'
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS'
export const GET_NOTIFICATION = 'GET_NOTIFICATION'
export const GET_NOTIFICATIONS_UNREAD_AMOUNT = 'GET_NOTIFICATIONS_UNREAD_AMOUNT'
export const ADD_UNREAD_NOTIFICATIONS_AMOUNT = 'ADD_UNREAD_NOTIFICATIONS_AMOUNT'
export const UPDATE_NOTIFICATION = 'UPDATE_NOTIFICATION'
export const CLEAR_NOTIFICATIONS = 'CLEAR_NOTIFICATIONS'
export const GET_NOTIFICATIONS_ERROR = 'GET_NOTIFICATIONS_ERROR'

// Auth
export const AUTH_LOADING = 'AUTH_LOADING'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const LOGOUT = 'LOGOUT'

// Meetings
export const UPDATE_CALENDAR_DATES = 'UPDATE_CALENDAR_DATES'
export const UPDATE_RESOURCE_MAP = 'UPDATE_RESOURCE_MAP'

export const MEETINGS_LOADING = 'MEETINGS_LOADING'
export const MEETINGS_CONNECT_WS = 'MEETINGS_CONNECT_WS'
export const LOAD_MEETINGS = 'LOAD_MEETINGS'
export const CHANGE_VISIBLE_MEETINGS = 'CHANGE_VISIBLE_MEETINGS'
export const ADD_LOADED_DATES = 'ADD_LOADED_DATES'
export const REMOVE_MEETING = 'REMOVE_MEETING'
export const UPDATE_MEETING = 'UPDATE_MEETING'
export const CLEAR_MEETINGS = 'CLEAR_MEETINGS'
